export const POSTS_FETCHED = "POSTS_FETCHED";
export const POSTS_LOADING = "POSTS_LOADING";
export const POST_CREATE = "POST_CREATE";
export const POST_FETCHED = "POST_FETCHED";

export const USER_FETCHED = "USER_FETCHED";
export const USERS_LOADING = "USERS_LOADING";

export const POST_COMMENTS_FETCHED = "POST_COMMENTS_FETCHED";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
